import Head from "next/head";
import Router from "next/router";
import { useState } from "react";

interface ContainerProps {
    children?: any,
    title: string
}
const Container: React.FC<ContainerProps> = ({children, title}) => {
  const [onOpen, setOnOpen] = useState(false);
  const onExit = () => {
    localStorage.clear();
    Router.replace("/login");
  };

  const onNavigate = (e: any, path: string) => {
    e.preventDefault();
    Router.push(path);
  };



  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span onClick={onExit} className="button-back-container">
        <img width={20} height={20} src={"/exit.png"} />
      </span>

      <span
        style={{ display: onOpen ? "none" : "flex" }}
        onClick={() => setOnOpen(!onOpen)}
        className="button-menu-container"
      >
        <img width={20} height={20} src={"/menu.png"} />
      </span>

      <div
        id="mySidenav"
        style={{ width: onOpen ? "250px" : "0px" }}
        className="sidenav"
      >
        <a href="#" onClick={() => setOnOpen(false)} className="closebtn">
          &times;
        </a>
        <a href="#" onClick={(e) => onNavigate(e, "/songs")}>
          Músicas
        </a>
        <a onClick={(e) => onNavigate(e, "/plans")} href="#">
          Planos
        </a>
        <a href="#" onClick={(e) => onNavigate(e, "/users")}>
          Usuários
        </a>
   
      </div>

      <main className="main-app">
        {children}
      </main>
    </div>
  );
};

export default Container;
